DROP TABLE IF EXISTS user_fridge_access;
DROP TABLE IF EXISTS fridges;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    userID INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 

CREATE TABLE fridges (
    fridgeID INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_fridge_access (
    userID INTEGER NOT NULL,
    fridgeID INTEGER NOT NULL,
    accessLevel VARCHAR(50) NOT NULL,
    PRIMARY KEY (userID, fridgeID),
    FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE,
    FOREIGN KEY (fridgeID) REFERENCES fridges(fridgeID) ON DELETE CASCADE
);
